services:
 mysql-order:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes:
    - mysql_order_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 reservation-service:
  depends_on:
    - product-service
    - inventory-service
  image: siebem03/reservation-service
  ports:
    - 8081:8081
  links:
    - product-service
    - inventory-service
  environment:
   PRODUCT_SERVICE_BASEURL: product-service:8080
   INVENTORY_INFO_SERVICE_BASEURL: inventory-service:8082
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-order
   MYSQL_DB_PORT: 3306

volumes:
 mongodb_product_data:
 mysql_inventory_data:
 mysql_order_data:
 