server:
  port: 7000

logging:
  level:
    root: INFO

spring:
  cloud:
    gateway:
      routes:
        - id: person-service-test
          uri: http://${PERSON_SERVICE_BASEURL:localhost:8095}
          predicates:
            - Path=/person/test
            - Method=GET
          filters:
            - SetPath=/api/person/test
        - id: bnb-service-test
          uri: http://${BNB_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/bnb/test
            - Method=GET
          filters:
            - SetPath=/api/bnb/test
        - id: reservation-service-test
          uri: http://${RESERVATION_SERVICE_BASEURL:localhost:8090}
          predicates:
            - Path=/reservation/test
            - Method=GET
          filters:
            - SetPath=/api/reservation/test